### ISSUE TITLE
API file of Freifunk Euskirchen

### ISSUE THREAD

**Issue by christian-weiss** [freifunkeu/website-new#4]
API file of Freifunk Euskirchen has some issues. 
See: https://github.com/freifunk/directory.api.freifunk.net/issues/591 for details.

We send 2 emails to kontakt@ffeu.de but did not get response.
That is the reason why we ask here for your feedback.

Please give feedback in https://github.com/freifunk/directory.api.freifunk.net/issues/591

@k3v1n-eu @ArwedSchmidt

**Comment by k3v1n-eu** [comment]
we have fixed the url to our meshviwer
